project_id = "wkinpwoqgevbntfuiejd"

[functions.notify-dealer-reassignment]
verify_jwt = true

[functions.create-commerciale]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.update-commerciale]
verify_jwt = true

[functions.delete-commerciale]
verify_jwt = true

[functions.assign-role]
verify_jwt = true

[functions.seed-test-data]
verify_jwt = true
